apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: quicksort
  namespace: knative-serverless
spec:
  template:
    metadata:
      annotations:
        # Knative concurrency-based autoscaling (default).
        autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
      - image: docker.io/wajrcs/quicksort-knative
        env:
        - name: TARGET
          value: "Python Sample v1"
