apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fibonacci-single
  namespace: knative-serverless
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/max-scale: "1"
    spec:
      containers:
      - image: docker.io/wajrcs/fibonacci-knative
        env:
        - name: TARGET
          value: "Python Sample v1"
